### PR TITLE
Add ruby script for transposing trainer retrospectives

### PR DESCRIPTION
**Pull request by brianamarie**
Hello @github/services-training & @swinton 👋 

This PR includes the ruby file that @swinton found for us and helped me test locally. ✨ 

This script corresponds to a pull request regarding a 'how-to' guide. 
([Link for hubbers, for reference](https://github.com/github/services-training/pull/74))

I will 🚢  after one 👍 .

### CODE REVIEW

**Comment by stoe** [comment]
@brianamarie, I refactored a little so that `transpose` is in line with our other scripts in this repo.
- The command now is `transpose foo.csv`, this will create a `foo-transposed.csv` output file.
- Moved the `transpose-csv.rb` file to a new `lib/` folder.
- Added description to the `README.md`.

**Comment by swinton** [comment]
> Moved the transpose-csv.rb file to a new lib/ folder.

Unfortunately, because of the way the bootstrap script works, now the `transpose` script can't find the `transpose-csv.rb` lib file:

```
/usr/local/bin/transpose: line 22: ./lib/transpose-csv.rb: No such file or directory
```

Having to install lib files somewhere where they can be found (e.g. `/usr/local/lib/`) feels like a big change. @stoe you :cool: with moving `transpose-csv.rb` back to the root directory, so it gets installed along with the other scripts?

**Comment by brianamarie** [comment]
@stoe Thank you for the 👀 and for the edits! 

@swinton I went ahead and moved the script back to the root directory.

**Comment by stoe** [comment]
> Having to install lib files somewhere where they can be found (e.g. `/usr/local/lib/`) feels like a big change. @stoe you 🆒 with moving `transpose-csv.rb` back to the root directory, so it gets installed along with the other scripts?

Sure. I haven't thought about that.
I'm not a fan of the `script/bootstrap` and then `Rakefile` way.

@swinton, please feel free to move and delete the `lib/` folder.

**Comment by swinton** [comment]
> @swinton, please feel free to move and delete the lib/ folder.

Will do, @stoe. @brianamarie I added myself as a co-assignee, I'll tend to my next step later today :+1:

**Comment by swinton** [comment]
:+1: :ok: think we are good here now, someone wanna put :eyes: on this one last time? @brianamarie @stoe?

**Comment by stoe** [comment]
> 🆗 think we are good here now, someone wanna put 👀 on this one last time?

Fixed the _path to transpose-csv.rb_ if not using `script/bootstrap` symlinking into `$PATH`.

@swinton @brianamarie, otherwise this looks :ship:able.

**Comment by swinton** [comment]
> Fixed the path to transpose-csv.rb if not using script/bootstrap symlinking into $PATH.

d2039bb is :sparkles:, thanks @stoe 

I say :+1: :ship:, @brianamarie?

**Pull request merged**
