### PR TITLE
Updated dependencies to clear dependabot warnings

### PR DESCRIPTION
**Pull request by gclhub**
Ref: https://github.com/github/vuln-mgmt/issues/57386

### CODE REVIEW

**Comment by gclhub** [comment]
Unable to request a reviewer in the UI, so tagging @github/professional-services for review here instead

**Review by stoe — APPROVED** [review]

**Comment by gclhub** [comment]
Thank you for the approval @stoe , can you merge since I don't have permission?

**Comment by stoe** [comment]
> can you merge since I don't have permission?

Me neither.
@ppremk, do you still have permissions?

**Review by arilivigni — APPROVED** [review]

**Comment by stoe** [comment]
@a-a-ron can you help us get this PR merged, please

**Comment by ppremk** [comment]
no access either

**Comment by steffen** [comment]
I pinged the admins of this repository [here](https://github.com/github/vuln-mgmt/issues/57386#issuecomment-1909982426).

**Comment by jenachiccino** [comment]
@steffen I merged the PR, hopefully I did what was needed. Let me know if there is anything else needed.

**Pull request merged**
