### PR TITLE
New Windows scripts to help setup a training environment

### LINKED ISSUE #17: Scripts to help setup a Developers PC into a Trainers PC
I recently went through GitHub's Certified Trainer sessions here at Ford.
One of the things that @brianamarie was rather **Harsh** on me about was my use of **alias'**.   :grin: 
Other items she mentioned as **Distractions** to students were **popup** messages and lots of bookmarks on your browsers toolbar.
In the Spirit of the training I came up with, rather quickly, a set of Windows :nauseated_face: batch files that help me setup my laptop to give training.
You can find them here: https://github.com/mblack88/training-scripts
@brianamarie thought they might make a decent contribution to your training utils, but I'm not sure how to bring in these Windows specific items into what you already have here.
I would like to start the discussion and see what all your thoughts are.

**Let the Fun Begin**

### PR DESCRIPTION
**Pull request by mblack88**
Here is the initial set of **Batch** files I have for setting up a training environment on a windows PC.  It is currently very specific to my environment.

new file:   windows/README.md
new file:   windows/killprogs.bat - Kill running programs that might
have popups.
new file:   windows/launch_ff.bat - Launch FireFox with base pages
new file:   windows/setalias.bat - Set normal alias' for trainer
new file:   windows/start_training.bat - Run the series of **bat** files
new file:   windows/unsetalias.bat - Unset nomral alias' for traininer

closes #17

### CODE REVIEW

**Comment by mblack88** [comment]
cc @github/services-training
@brianamarie  @crichID adding you guys to the conversation for good measure

**Comment by brianamarie** [comment]
@mblack88 This is awesome! I have some time on my calendar to look at these more in depth later, but I wanted you to know that I saw them. Also, cc @github/services-training for heads up to scripts!

**Comment by mblack88** [comment]
Ping Do we want to just close this with no future activity?  It seems to have died on the vine.

**Comment by crichID** [comment]
> Do we want to just close this with no future activity? It seems to have died on the vine.

😱 yikes, this one definitely got a little stale. Have you been using these scripts? If so, I think we should go ahead and merge them in.

**Comment by mblack88** [comment]
I do run this prior to giving training.

Sent from my iPhone

On Sep 4, 2018, at 10:09 PM, Cynthia Rich <notifications@github.com<mailto:notifications@github.com>> wrote:


Do we want to just close this with no future activity? It seems to have died on the vine.

😱 yikes, this one definitely got a little stale. Have you been using these scripts? If so, I think we should go ahead and merge them in.

**Comment by crichID** [comment]
> I do run this prior to giving training.

@mblack88 :+1: in that case let's ship this. The README for the folder is very well done and shows how to customize it. I think this will be an excellent addition, thank you for contributing these utilities.

**Pull request merged**
